<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selectable Date Display_selected-date</name>
   <tag></tag>
   <elementGuidId>39ce56a1-b51b-46ab-9ddd-2334cd195ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selected-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;selected-date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e086ab89-1ad5-4a66-80d0-27b188cb3fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>434dceaa-9ba7-406b-b7b6-0c2e14e0a7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selected-date</value>
      <webElementGuid>0164bc3e-7626-4242-bedf-543271a4bc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selected-date&quot;)</value>
      <webElementGuid>a0272d35-34a0-49c7-bced-a28cb7621b54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selected-date']</value>
      <webElementGuid>476cad84-e254-4f0f-b6ac-c50e2c9805db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e78bbf89-8325-491d-8c1c-dfb7cf46f790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'selected-date']</value>
      <webElementGuid>71322289-a69d-4e04-a16f-d11573157688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
